#!/bin/sh
### BEGIN INIT INFO
# Provides:          core
# Short-Description: Start the EBS core daemon.
### END INIT INFO
trap '' 1 2 3 15


DAEMON=/ebs/core/data/core
NAME=core
DESC="ebs billing core daemon"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/ebs_$NAME
ERR_LOG=/ebs/core/data/log/log.txt
EXEC_DIR=/ebs/core/data

test -x $DAEMON || exit 0

case "$1" in
start)
        
         echo "Starting ebs core"
			$DAEMON &

		;;
stop)
        echo "Stopping ebs core"
	if [ `uname` = 'SunOS' ]
	then
	    pkill -SIGTERM -x $NAME
	    sleep 25
	    pkill -9 -x $DAEMON
	else
        killall -SIGTERM $NAME
        sleep 25
        killall -9 $NAME
	fi
        ;;
stop-force)
        echo "Stopping ebs core"
    if [ `uname` = 'SunOS' ]
    then
        pkill -9 -x $NAME
    else
        killall -9 $NAME
    fi
        ;;
restart)
        echo "Restarting ebs core"
    $0 stop
    $0 start
        ;;
reload)
        echo "Reloading ebs core configuration"
    if [ `uname` = 'SunOS' ]
    then
        pkill -SIGHUP -x $NAME
    else
        killall -SIGHUP $NAME
    fi
        ;;
*)
        echo "Usage: `basename $0` {start|stop|stop-force|reload}" >&2
        exit 64
        ;;
esac
