#!/bin/sh
### BEGIN INIT INFO
# Provides:          nffilter
# Required-Start:    $postgres $syslog $local_fs $network
# Required-Stop:     $syslog $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the EBS nffilter daemon.
### END INIT INFO
trap '' 1 2 3 15


NAME=nffilter
DPATH=/opt/ebs/data/
DAEMON=$DPATH$NAME

DESC="ebs billing nffilter daemon"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/ebs_$NAME
ERR_LOG=/opt/ebs/data/log/log.txt
EXEC_DIR=/opt/ebs/data/

test -x $DAEMON || exit 0

case "$1" in
start)
        
        echo "Starting ebs nffilter"
		olddir=`pwd`
        cd $DPATH
        $DAEMON &
        cd $olddir

		;;
stop)
        echo "Stopping ebs nffilter"
	if [ `uname` = 'SunOS' ]
	then
	    pkill -SIGTERM -x $NAME
	    sleep 10
	    pkill -9 -x $DAEMON
	else
        killall -SIGTERM $NAME
        sleep 10
        killall -9 $NAME
	fi
	rm -f $PIDFILE
        ;;
stop-force)
        echo "Stopping ebs nffilter"
    if [ `uname` = 'SunOS' ]
    then
        pkill -9 -x $NAME
    else
        killall -9 $NAME
    fi
    rm -f $PIDFILE
        ;;
restart)
        echo "Restarting ebs nffilter"
    $0 stop
    $0 start
        ;;
reload)
        echo "Reloading ebs nffilter configuration"
    if [ `uname` = 'SunOS' ]
    then
        pkill -SIGHUP -x $NAME
    else
        killall -SIGHUP $NAME
    fi
        ;;
*)
        echo "Usage: `basename $0` {start|stop|stop-force|reload}" >&2
        exit 64
        ;;
esac
