#!/bin/sh
### BEGIN INIT INFO
# Provides:          rpc
# Short-Description: Start the EBS rpc daemon.
### END INIT INFO
trap '' 1 2 3 15


DAEMON=/opt/ebs/data/rpc
NAME=rpc
DESC="ebs billing rpc daemon"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/ebs_$NAME
ERR_LOG=/opt/ebs/data/log/log.txt
EXEC_DIR=/opt/ebs/data/

test -x $DAEMON || exit 0

case "$1" in
start)
        
         echo "Starting ebs rpc"
			$DAEMON &

		;;
stop)
        echo "Stopping ebs rpc"
	if [ `uname` = 'SunOS' ]
	then
	    pkill -SIGTERM -x $NAME
	    sleep 5
	    pkill -9 -x $DAEMON
	else
        killall -SIGTERM $NAME
        sleep 5
        killall -9 $NAME
	fi
        ;;
stop-force)
        echo "Stopping ebs rpc"
    if [ `uname` = 'SunOS' ]
    then
        pkill -9 -x $NAME
    else
        killall -9 $NAME
    fi
        ;;
restart)
        echo "Restarting ebs rpc"
    $0 stop
    $0 start
        ;;
reload)
        echo "Reloading ebs rpc configuration"
    if [ `uname` = 'SunOS' ]
    then
        pkill -SIGHUP -x $NAME
    else
        killall -SIGHUP $NAME
    fi
        ;;
*)
        echo "Usage: `basename $0` {start|stop|stop-force|reload}" >&2
        exit 64
        ;;
esac
