# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 16:41
from __future__ import unicode_literals

from django.db import migrations, models

from billservice.models import AccessParameters, TimeSpeed


def chr_to_int(c):
    if not c:
        return 0
    elif c.endswith('k'):
        return int(c.rstrip('k')) * 1024
    elif c.endswith('M'):
        return int(c.rstrip('M')) * 1024 * 1024
    try:
        return int(c)
    except ValueError:
        return int(float(c))


def update_db(*_):
    fields = ('max_tx', 'max_rx', 'burst_tx',
              'burst_rx', 'burst_treshold_tx',
              'burst_treshold_rx', 'burst_time_tx',
              'burst_time_rx', 'min_tx', 'min_rx')
    for model in (AccessParameters, TimeSpeed):
        items = model.objects.all()
        for item in items:
            for field in fields:
                setattr(item, field + '_int', chr_to_int(getattr(item, field)))
                item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessparameters',
            name='burst_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst Rx'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='burst_time_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst time Rx (s)'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='burst_time_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst time Tx (s)'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='burst_treshold_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst treshold Rx'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='burst_treshold_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst treshold Tx'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='burst_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst Tx'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='max_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Max Rx'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='max_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Max Tx'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='min_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Min Rx'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='min_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Min Tx'),
        ),
        migrations.AddField(
            model_name='accessparameters',
            name='speed_units',
            field=models.CharField(blank=True, choices=[(b'Kbps', b'Kbps'), (b'Mbps', b'Mbps'), (b'%', b'%')], max_length=32, null=True,
                                   verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u044b \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='burst_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst Rx'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='burst_time_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst time Rx (s)'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='burst_time_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst time Tx (s)'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='burst_treshold_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst treshold Rx'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='burst_treshold_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst treshold Tx'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='burst_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst Tx'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='max_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Max Rx'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='max_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Max Tx'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='min_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Min Rx'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='min_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Min Tx'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='priority',
            field=models.IntegerField(
                blank=True, default=8, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='speed_units',
            field=models.CharField(blank=True, choices=[(b'Kbps', b'Kbps'), (b'Mbps', b'Mbps'), (b'%', b'%')], max_length=32, null=True,
                                   verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u044b \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='burst_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst Rx'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='burst_time_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst time Rx (s)'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='burst_time_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst time Tx (s)'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='burst_treshold_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst treshold Rx'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='burst_treshold_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst treshold Tx'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='burst_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Burst Tx'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='max_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Max Rx'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='max_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Max Tx'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='min_rx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Min Rx'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='min_tx_int',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='Min Tx'),
        ),
        migrations.AddField(
            model_name='timespeed',
            name='speed_units',
            field=models.CharField(blank=True, choices=[(b'Kbps', b'Kbps'), (b'Mbps', b'Mbps'), (b'%', b'%')], max_length=32, null=True,
                                   verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u044b \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='priority',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='speed_units',
            field=models.CharField(blank=True, choices=[(b'Kbps', b'Kbps'), (b'Mbps', b'Mbps'), (b'%', b'%')], max_length=32, null=True,
                                   verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u044b \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='priority',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='speed_units',
            field=models.CharField(blank=True, choices=[(b'Kbps', b'Kbps'), (b'Mbps', b'Mbps'), (b'%', b'%')], max_length=32, null=True,
                                   verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u044b \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438'),
        ),

        migrations.RunPython(update_db)
    ]
