# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billservice', '0003_auto_20170915_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonservice',
            name='burst_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst Rx'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='burst_time_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst time Rx (s)'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='burst_time_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst time Tx (s)'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='burst_treshold_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst treshold Rx'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='burst_treshold_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst treshold Tx'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='burst_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst Tx'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='max_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Max Rx'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='max_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Max Tx'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='min_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Min Rx'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='min_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Min Tx'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='burst_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst Rx'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='burst_time_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst time Rx (s)'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='burst_time_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst time Tx (s)'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='burst_treshold_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst treshold Rx'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='burst_treshold_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst treshold Tx'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='burst_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Burst Tx'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='max_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Max Rx'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='max_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Max Tx'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='min_rx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Min Rx'),
        ),
        migrations.AlterField(
            model_name='speedlimit',
            name='min_tx',
            field=models.IntegerField(blank=True, default=0, verbose_name='Min Tx'),
        ),
    ]
