# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billservice', '0003_auto_20170915_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speedlimit',
            old_name='t_tx',
            new_name='burst_tx',
        ),
    ]
