# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billservice', '0005_auto_20170918_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subaccount',
            old_name='burst_rx_int',
            new_name='burst_rx',
        ),
        migrations.RenameField(
            model_name='subaccount',
            old_name='burst_time_rx_int',
            new_name='burst_time_rx',
        ),
        migrations.RenameField(
            model_name='subaccount',
            old_name='burst_time_tx_int',
            new_name='burst_time_tx',
        ),
        migrations.RenameField(
            model_name='subaccount',
            old_name='burst_treshold_rx_int',
            new_name='burst_treshold_rx',
        ),
        migrations.RenameField(
            model_name='subaccount',
            old_name='burst_treshold_tx_int',
            new_name='burst_treshold_tx',
        ),
        migrations.RenameField(
            model_name='subaccount',
            old_name='burst_tx_int',
            new_name='burst_tx',
        ),
        migrations.RenameField(
            model_name='subaccount',
            old_name='max_rx_int',
            new_name='max_rx',
        ),
        migrations.RenameField(
            model_name='subaccount',
            old_name='max_tx_int',
            new_name='max_tx',
        ),
        migrations.RenameField(
            model_name='subaccount',
            old_name='min_rx_int',
            new_name='min_rx',
        ),
        migrations.RenameField(
            model_name='subaccount',
            old_name='min_tx_int',
            new_name='min_tx',
        ),
    ]
