# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:25
from __future__ import unicode_literals

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billservice', '0006_auto_20170920_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AlterModelOptions(
            name='accountviewednews',
            options={'ordering': ('-news__created',)},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'permissions': (('news_view', '\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440'),), 'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c', 'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'},
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0410\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u0430 \u0441'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(default='', help_text='\u041d\u0435 \u0431\u043e\u043b\u0435\u0435 64 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432', max_length=64, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
