#!/bin/sh -e
#$1 - project name $2 users $3 key $4 license string

python lic_generator.py $1 $2 $4
if [ ! -d builds ]; then
	mkdir builds
fi
reskey=""
karg=""

if [ $3 ]; then
	karg="-k"
	reskey=$3`cat license_$1.lic`
fi

if [ $reskey ]; then
	echo $reskey;
else
    echo "No key entered - test drive";
fi

rm -rf modules
rm -rf builds/$1

mkdir builds/$1





simple_build="rad_ "
total_build="core_ nf_ nfroutine_ $simple_build"

cp license.lic license.lic.old
cp license_$1.lic license.lic

python freezer/freezer.py --order=utilites,classes,classes.cache_sql,classes.core_class,classes.core_class.NasData,classes.core_class.RadiusSession,classes.core_class.AccountData,classes.core_class.OneTimeServiceData,classes.core_class.IpnSpeedData,classes.core_class.BillSession,classes.core_class.TimeAccessNodeData,classes.core_class.AccessParametersDefault,classes.core_class.TimePeriodNodeData,classes.core_class.SettlementPeriodData,classes.core_class.TrafficLimitData,classes.core_class.AccessParametersData,classes.core_class.TimeAccessServiceData,classes.core_class.SpeedParameters,classes.core_class.TrafficTransmitSData,classes.core_class.PeriodicalServiceSettlementData,classes.core_class.ShedulelogData,classes.cacheutils,classes.core_cache,classes.flags -i $karg $reskey core_.py > builds/$1.core_.buildlog

python freezer/freezer.py --order=utilites,classes,classes.cache_sql,classes.common,classes.nf_class,classes.cacheutils,classes.nf_class.GroupsData,classes.nf_class.ClassData,classes.common.Flow5Data,classes.nf_class.AccountData,classes.nf_cache,classes.vars,classes.flags -i $karg $reskey nf_.py > builds/$1.nf_.buildlog

python freezer/freezer.py --order=utilites,classes,classes.cache_sql,classes.nfroutine_class,classes.cacheutils,classes.nfroutine_class.NodesData,classes.common,classes.nfroutine_class.TrafficTransmitServiceData,classes.common.Flow5Data,classes.nfroutine_class.SettlementData,classes.nfroutine_class.AccountData,classes.nfroutine_cache,classes.flags,classes.vars -i $karg $reskey nfroutine_.py > builds/$1.nfroutine_.buildlog

for bld in $simple_build; do
	python freezer/freezer.py  -i $karg $reskey $bld.py > builds/$1.$bld.buildlog;
done


cp license.lic builds/$1/license.lic
cp license.lic.old license.lic
cp ebs_config.ini builds/$1/ebs_config.ini 
cp -rf modules builds/$1
mkdir builds/$1/nf_dump
mkdir builds/$1/log
mkdir builds/$1/init.d
cp -rf dicts builds/$1/dicts
cp -rf fonts builds/$1/fonts
rm -rf builds/$1/modules/chartprovider
cp chartprovider/pychartdir.pyc chartprovider/pychartdir25.pyd chartprovider/pychartdir25.so chartprovider/libchartdir.so builds/$1/modules
svn export --username dolphinik --password planeta svn://127.0.0.1/mikrobill/trunk/webadmin/ebscab ebscab/ --force

mkdir builds/$1/ebscab
cp -r ebscab/ builds/$1/ebscab/
mkdir builds/$1/sql
cp sql/ebs_dump.sql builds/$1/sql/
cp sql/changes.sql builds/$1/sql/


for bldd in $total_build; do
	cp $bldd builds/$1
	#cp init/ebs_$bldd builds/$1/init.d/ebs_$bldd
	#chmod +x builds/$1/init.d/ebs_$bldd
done

find $1 -name '.svn' -type d | xargs rm -rf

if [ $SUDO_USER ]; then
	chown -hR $SUDO_USER: builds/$1
fi

cd builds/$1/
tar -czvf ../$1.tar.gz .
cd ../../

