DATABASE_ENGINE = 'postgresql_psycopg2'
DATABASE_NAME = 'ebs_test'
#DATABASE_USER = 'ebs'
#DATABASE_PASSWORD = 'ebspassword'

DATABASE_USER = 'postgres'
DATABASE_PASSWORD = 'Ahch1woi'

DATABASE_HOST = '127.0.0.1'
DATABASE_PORT = '5432'

ROOT_URLCONF = 'urls'
