#-*-coding=utf-8-*-

DATABASE_NAME='ebs6'
DATABASE_HOST='localhost'
DATABASE_USER='mikrobill'
DATABASE_PASSWORD='1234'

BYTES_IN_KB=1024
LOG=False
LOG_LOCATION='./'

NF_HOST = '0.0.0.0'
NF_PORT = 9996
