INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Сбросить RADIUS сессию','radius','reset_activesession',1);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять RADIUS сессию','radius','delete_activesession',2);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать RADIUS сессии','radius','view_activesession',3);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать лог RADIUS авторизаций','radius','view_authlog',4);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять лог RADIUS авторизаций','radius','delete_authlog',5);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Сервер доступа','nas','add_nas',6);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Сервер доступа','nas','change_nas',7);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Сервер доступа','nas','delete_nas',8);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Сервер доступа','nas','view_nas',9);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Класс трафика','nas','add_trafficclass',10);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Класс трафика','nas','change_trafficclass',11);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Класс трафика','nas','delete_trafficclass',12);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Класс трафика','nas','view_trafficclass',13);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Направление трафика','nas','add_trafficnode',14);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Направление трафика','nas','change_trafficnode',15);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Направление трафика','nas','delete_trafficnode',16);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Направление трафика','nas','view_trafficnode',17);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Ноду временного периода','billservice','create_timeperiodnode',18);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Ноду временного периода','billservice','change_timeperiodnode',19);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Ноду временного периода','billservice','delete_timeperiodnode',20);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать ноду временного периода','billservice','view_timeperiodnode',21);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Временной период','billservice','add_timeperiod',22);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Временной период','billservice','change_timeperiod',23);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Временной период','billservice','delete_timeperiod',24);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Временной период','billservice','view_timeperiod',25);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Расчетный период','billservice','add_settlementperiod',26);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Расчетный период','billservice','change_settlementperiod',27);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Расчетный период','billservice','delete_settlementperiod',28);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать расчётный период','billservice','view_settlementperiod',29);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Перетарификация периодических услуг','billservice','change_periodicalservicehistory',30);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять списания по периодиеским услугам','billservice','delete_periodicalservicehistory',31);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать списание по периодическим услугам','billservice','periodicalservicehistory_view',32);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Списание по разовым услугам','billservice','change_onetimeservicehistory',33);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Списание по разовым услугам','billservice','delete_onetimeservicehistory',34);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать списание по разовым услугам','billservice','view_onetimeservicehistory',35);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Период доступа','billservice','add_timeaccessnode',36);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Период доступа','billservice','change_timeaccessnode',37);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Период доступа','billservice','delete_timeaccessnode',38);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать период доступа','billservice','view_timeacessnode',39);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать предоплаченный NetFlow трафик','billservice','view_account_prepaystraffic',40);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Предоплаченый radius трафик аккаунта ','billservice','add_accountprepaysradiustrafic',41);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Предоплаченый radius трафик аккаунта','billservice','change_accountprepaysradiustrafic',42);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Предоплаченый radius трафик аккаунта ','billservice','delete_accountprepaysradiustrafic',43);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать предоплаченный NetFlow трафик','billservice','view_accountprepaysradiustraffic',44);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Предоплаченное время пользователя','billservice','add_accountprepaystime',45);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Предоплаченное время пользователя','billservice','change_accountprepaystime',46);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Предоплаченное время пользователя','billservice','delete_accountprepaystime',47);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Предоплаченное время пользователя','billservice','view_accountprepaystime',48);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Тариф','billservice','add_tariff',49);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Тариф','billservice','change_tariff',50);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Тариф','billservice','delete_tariff',51);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Тариф','billservice','view_tariff',52);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Аккаунт','billservice','add_account',53);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Аккаунт','billservice','change_account',54);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Аккаунт','billservice','delete_account',55);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Аккаунт','billservice','view_account',56);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Получить тариф для аккаунта','billservice','get_tariff',57);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Список аккаунтов для кассира','billservice','view_cashier',58);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Тип проводки','billservice','add_transactiontype',59);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Тип проводки','billservice','change_transactiontype',60);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Тип проводки','billservice','delete_transactiontype',61);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Тип проводки','billservice','view_transactiontype',62);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Проводку','billservice','add_transaction',63);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Проводку','billservice','change_transaction',64);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Проводку','billservice','delete_transaction',65);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Проводку','billservice','view_transaction',66);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Тариф аккаунта','billservice','add_accounttarif',67);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Тариф аккаунта','billservice','change_accounttarif',68);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Тариф аккаунта','billservice','delete_accounttarif',69);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Историю периодических операций','billservice','change_shedulelog',70);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Историю периодических операций','billservice','delete_shedulelog',71);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Системного пользователя','billservice','add_systemuser',72);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Системного пользователя','billservice','change_systemuser',73);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Системного пользователя','billservice','delete_systemuser',74);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Системного пользователя','billservice','view_systemuser',75);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Получение любой модели методом get_model','billservice','get_model',76);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменение IPN статуса на сервере доступа','billservice','actions_set',77);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Серверный рендеринг документов','billservice','documentrender',78);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Тестирование данных для сервера доступа','billservice','testcredentials',79);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Получение статуса портов коммутатора','billservice','getportsstatus',80);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Установка статуса портов коммутатора','billservice','setportsstatus',81);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Список лог-файлов биллинга','billservice','list_log_files',82);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать лог-файлы биллинга','billservice','view_log_files',83);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удаление проводок','billservice','transactions_delete',84);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Метод sp_info','billservice','sp_info',85);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Шаблон','billservice','add_template',86);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Шаблон','billservice','change_template',87);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Шаблон','billservice','delete_template',88);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Шаблон','billservice','view_template',89);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Карты','billservice','add_card',90);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Карты','billservice','change_card',91);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Карты','billservice','delete_card',92);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Карты','billservice','view_card',93);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Информация о провайдере','billservice','add_operator',94);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Информация о провайдере','billservice','change_operator',95);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать информацию о провайдере','billservice','view_operator',96);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Дилера','billservice','add_dealer',97);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Дилера','billservice','change_dealer',98);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Дилера','billservice','delete_dealer',99);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Дилера','billservice','view_dealer',100);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Накладную на карты','billservice','add_salecard',101);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Накладную на карты','billservice','change_salecard',102);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Накладную на карты','billservice','delete_salecard',103);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать накладную на карты','billservice','view_salecard',104);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Платёж дилера','billservice','add_dealerpay',105);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Платёж дилера','billservice','change_dealerpay',106);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Платёж дилера','billservice','delete_dealerpay',107);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Платеж дилера','billservice','view_dealerpay',108);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Документ','billservice','add_document',109);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Документ','billservice','change_document',110);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Документ','billservice','delete_document',111);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Период без списаний','billservice','add_suspendedperiod',112);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Период без списаний','billservice','change_suspendedperiod',113);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Период без списаний','billservice','delete_suspendedperiod',114);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать период без списаний','billservice','view_suspendedperiod',115);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Группу трафика','billservice','add_group',116);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Группу трафика','billservice','change_group',117);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Группу трафика','billservice','delete_group',118);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать группу трафика','billservice','view_group',119);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать тарифицированный трафик','billservice','view_groupstat',120);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять тарифицированный трафик','billservice','delete_groupstat',121);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать IP пул','billservice','add_ippool',122);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять IP пул','billservice','change_ippool',123);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять IP пул','billservice','delete_ippool',124);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать IP пул','billservice','view_ippool',125);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Занятый IP адрес','billservice','change_ipinuse',126);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Занятый IP адрес','billservice','delete_ipinuse',127);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Занятый IP адрес','billservice','view_ipinuse',128);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Списание за трафик','billservice','change_traffictransaction',129);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Списание за трафик','billservice','delete_traffictransaction',130);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Правило смены тарифов','billservice','add_tpchangerule',131);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Правило смены тарифов','billservice','change_tpchangerule',132);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Правило смены тарифов','billservice','delete_tpchangerule',133);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Правило смены тарифов','billservice','view_tpchangerule',134);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Custom RADIUS атрибут','billservice','add_radiusattrs',135);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Custom RADIUS атрибут','billservice','change_radiusattrs',136);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Custom RADIUS атрибут','billservice','delete_radiusattrs',137);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Custom RADIUS атрибут','billservice','view_radiusattrs',138);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Подключаемую услугу','billservice','add_addonservice',139);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Подключаемую услугу','billservice','change_addonservice',140);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Подключаемую услугу','billservice','delete_addonservice',141);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Подключаемую услугу','billservice','view_addonservice',142);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Подключаемую услугу аккаунта','billservice','add_accountaddonservice',143);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Подключаемую услугу аккаунта','billservice','change_accountaddonservice',144);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Подключаемую услугу аккаунта','billservice','delete_accountaddonservice',145);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Списание по подключаемой услуге','billservice','change_addonservicetransaction',147);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Списание по подключаемой услуге','billservice','delete_addonservicetransaction',148);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Новость','billservice','add_news',149);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Новость','billservice','change_news',150);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Новость','billservice','delete_news',151);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Новость','billservice','view_news',152);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Субаккаунт','billservice','add_subaccount',153);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Субаккаунт','billservice','change_subaccount',154);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Субаккаунт','billservice','delete_subaccount',155);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Субаккаунт','billservice','view_subaccount',156);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Получение mac адреса по IP','billservice','getmacforip',157);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Историю изменения баланса','billservice','view_balancehistory',158);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Город','billservice','add_city',159);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Город','billservice','change_city',160);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Город','billservice','delete_city',161);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Город','billservice','view_city',162);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Улицу','billservice','add_street',163);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Улицу','billservice','change_street',164);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Улицу','billservice','delete_street',165);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Улицу','billservice','view_street',166);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Дом','billservice','add_house',167);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Дом','billservice','change_house',168);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Дом','billservice','delete_house',169);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Дом','billservice','view_house',170);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Шаблон номера договора','billservice','add_contracttemplate',171);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Шаблон номера договора','billservice','change_contracttemplate',172);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Шаблон номера договора','billservice','delete_contracttemplate',173);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Шаблон номера договора','billservice','view_contracttemplate',174);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Производителя','billservice','add_manufacturer',175);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Производителя','billservice','change_manufacturer',176);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Производителя','billservice','delete_manufacturer',177);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Производителя','billservice','view_manufacturer',178);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Тип оборудования','billservice','add_hardwaretype',179);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Тип оборудования','billservice','change_hardwaretype',180);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Тип оборудования','billservice','delete_hardwaretype',181);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Тип оборудования','billservice','view_hardwaretype',182);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Модель оборудования','billservice','add_model',183);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Модель оборудования','billservice','change_model',184);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Модель оборудования','billservice','delete_model',185);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Модель оборудования','billservice','view_model',186);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Устройство','billservice','add_hardware',187);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Устройство','billservice','change_hardware',188);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Устройство','billservice','delete_hardware',189);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Устройство','billservice','view_hardware',190);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Устройств у абонента','billservice','add_accounthardware',191);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Устройство у абонента','billservice','change_accounthardware',192);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Устройство у абонента','billservice','delete_accounthardware',193);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Устройство у абонента','billservice','view_accounthardware',194);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять periodical service log','billservice','change_periodicalservicelog',195);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять periodical service log','billservice','delete_periodicalservicelog',196);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать периоды без периодических услуг','billservice','view_suspendedperiod',197);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Выполнение любого sql запроса','billservice','rawsqlexecution',199);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Группу абонентов','billservice','add_accountgroup',200);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Группу абонентов','billservice','change_accountgroup',201);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Группу абонентов','billservice','delete_accountgroup',202);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Группу абонентов','billservice','view_accountgroup',203);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Создавать Коммутатор','billservice','add_switch',204);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Изменять Коммутатор','billservice','change_switch',205);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Удалять Коммутатор','billservice','delete_switch',206);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать Коммутатор','billservice','view_switch',207);
INSERT INTO billservice_permission(name, app, internal_name, ordering) VALUES('Просматривать лог действий','object_log','view_logitem',208);

ALTER TABLE billservice_permission ADD CONSTRAINT billservice_permission_name_app_internal_name_uniq UNIQUE (name, app, internal_name);
