INSERT INTO helpdesk_queue (id, title, slug, email_address, locale, allow_public_submission, allow_email_submission, escalate_days, new_ticket_cc, updated_ticket_cc, email_box_type, email_box_host, email_box_port, email_box_ssl, email_box_user, email_box_pass, email_box_imap_folder, email_box_interval, email_box_last_check) VALUES (2, 'Новое подключение', 'nc', 'helpdesk@isp.net', NULL, true, false, NULL, '', '', NULL, NULL, NULL, false, NULL, NULL, NULL, 5, NULL);

INSERT INTO helpdesk_queue (id, title, slug, email_address, locale, allow_public_submission, allow_email_submission, escalate_days, new_ticket_cc, updated_ticket_cc, email_box_type, email_box_host, email_box_port, email_box_ssl, email_box_user, email_box_pass, email_box_imap_folder, email_box_interval, email_box_last_check) VALUES (4, 'Вирусы', 'virus', 'provider@isp.net', NULL, true, false, NULL, '', '', NULL, NULL, NULL, false, NULL, NULL, NULL, 5, NULL);

INSERT INTO helpdesk_queue (id, title, slug, email_address, locale, allow_public_submission, allow_email_submission, escalate_days, new_ticket_cc, updated_ticket_cc, email_box_type, email_box_host, email_box_port, email_box_ssl, email_box_user, email_box_pass, email_box_imap_folder, email_box_interval, email_box_last_check) VALUES (3, 'Авария', 'crash', 'helpdesk@isp.net', NULL, true, false, NULL, '', '', NULL, NULL, NULL, false, NULL, NULL, NULL, 5, NULL);

INSERT INTO helpdesk_queue (id, title, slug, email_address, locale, allow_public_submission, allow_email_submission, escalate_days, new_ticket_cc, updated_ticket_cc, email_box_type, email_box_host, email_box_port, email_box_ssl, email_box_user, email_box_pass, email_box_imap_folder, email_box_interval, email_box_last_check) VALUES (5, 'Проблемы в работе сети', 'neterr', 'helpdesk@isp.net', NULL, true, false, NULL, '', '', NULL, NULL, NULL, false, NULL, NULL, NULL, 5, NULL);

INSERT INTO helpdesk_queue (id, title, slug, email_address, locale, allow_public_submission, allow_email_submission, escalate_days, new_ticket_cc, updated_ticket_cc, email_box_type, email_box_host, email_box_port, email_box_ssl, email_box_user, email_box_pass, email_box_imap_folder, email_box_interval, email_box_last_check) VALUES (6, 'Доступ в интернет', 'internet', 'helpdesk@isp.net', NULL, true, false, NULL, '', '', NULL, NULL, NULL, false, NULL, NULL, NULL, 5, NULL);

INSERT INTO helpdesk_queue (id, title, slug, email_address, locale, allow_public_submission, allow_email_submission, escalate_days, new_ticket_cc, updated_ticket_cc, email_box_type, email_box_host, email_box_port, email_box_ssl, email_box_user, email_box_pass, email_box_imap_folder, email_box_interval, email_box_last_check) VALUES (7, 'Изменение учётных данных', 'ch-acc', 'helpdesk@isp.net', NULL, true, false, NULL, '', '', NULL, NULL, NULL, false, NULL, NULL, NULL, 5, NULL);

INSERT INTO helpdesk_queue (id, title, slug, email_address, locale, allow_public_submission, allow_email_submission, escalate_days, new_ticket_cc, updated_ticket_cc, email_box_type, email_box_host, email_box_port, email_box_ssl, email_box_user, email_box_pass, email_box_imap_folder, email_box_interval, email_box_last_check) VALUES (8, 'Вопросы по расчётам', 'billing', 'helpdesk@isp.net', NULL, true, false, NULL, '', '', NULL, NULL, NULL, false, NULL, NULL, NULL, 5, NULL);
