# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nas',
            name='speed_vendor_1',
        ),
        migrations.RemoveField(
            model_name='nas',
            name='speed_vendor_2',
        ),
        migrations.AddField(
            model_name='nas',
            name='subacc_ipn_speed_add_action',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='Add IPN speed command'),
        ),
        migrations.AddField(
            model_name='nas',
            name='subacc_ipn_speed_remove_action',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='Remove IPN speed command'),
        ),
        migrations.AddField(
            model_name='nas',
            name='subacc_vpn_speed_change_action',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='Change VPN speed command'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='speed_attr_id1',
            field=models.CharField(blank=True, default=b'', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='nas',
            name='speed_attr_id2',
            field=models.CharField(blank=True, default=b'', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='nas',
            name='subacc_ipn_speed_action',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='Change IPN speed command'),
        ),
    ]
