# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nas',
            options={'permissions': (('nas_view', '\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440'),), 'verbose_name': '\u0421\u0435\u0440\u0432\u0435\u0440 \u0434\u043e\u0441\u0442\u0443\u043f\u0430', 'verbose_name_plural': '\u0421\u0435\u0440\u0432\u0435\u0440\u044b \u0434\u043e\u0441\u0442\u0443\u043f\u0430'},
        ),
        migrations.AlterField(
            model_name='nas',
            name='subacc_ipn_speed_action',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='Set IPN speed command'),
        ),
    ]
