# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0002_auto_20171216_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='nas',
            name='radius_speed_attr1',
            field=models.CharField(blank=True, default=b'', max_length=128, null=True, verbose_name='Radius Speed attribute 1'),
        ),
        migrations.AddField(
            model_name='nas',
            name='radius_speed_attr2',
            field=models.CharField(blank=True, default=b'', max_length=128, null=True, verbose_name='Radius Speed attribute 2'),
        ),
        migrations.AddField(
            model_name='nas',
            name='radius_speed_value1',
            field=models.TextField(blank=True, default=b'', verbose_name='Radius Speed value 1'),
        ),
        migrations.AddField(
            model_name='nas',
            name='radius_speed_value2',
            field=models.TextField(blank=True, default=b'', verbose_name='Radius Speed value 2'),
        ),
        migrations.AddField(
            model_name='nas',
            name='subacc_ipn_speed_add_action',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='Add IPN speed command'),
        ),
        migrations.AddField(
            model_name='nas',
            name='subacc_ipn_speed_remove_action',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='Remove IPN speed command'),
        ),
        migrations.AddField(
            model_name='nas',
            name='subacc_vpn_speed_change_action',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='Change VPN speed command'),
        ),
    ]
