# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import ebscab.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0003_auto_20171216_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nas',
            name='identify',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RADIUS \u0438\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='radius_speed_value1',
            field=models.CharField(blank=True, default=b'', max_length=128, null=True, verbose_name='Radius Speed value 1'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='radius_speed_value2',
            field=models.CharField(blank=True, default=b'', max_length=128, null=True, verbose_name='Radius Speed value 2'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='secret',
            field=ebscab.fields.EncryptedTextField(blank=True, help_text='\u0421\u043c\u043e\u0442\u0440\u0438\u0442\u0435 \u0432\u044b\u0432\u043e\u0434 \u043a\u043e\u043c\u0430\u043d\u0434\u044b /radius print', max_length=255, null=True, verbose_name='\u0421\u0435\u043a\u0440\u0435\u0442\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430'),
        ),
    ]
