# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billservice', '0007_auto_20171110_1425'),
        ('nas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(blank=True, max_length=255, verbose_name='ID')),
                ('interrim_update', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0435 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0435')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0435\u0446')),
                ('caller_id', models.CharField(blank=True, max_length=255, verbose_name='Caller ID')),
                ('called_id', models.CharField(blank=True, max_length=255, verbose_name='Called ID')),
                ('framed_ip_address', models.CharField(blank=True, default=b'', max_length=255, verbose_name='IP')),
                ('nas_id', models.CharField(blank=True, max_length=255, verbose_name='Nas ID')),
                ('session_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('framed_protocol', models.CharField(choices=[('PPTP/L2TP', 'PPTP'), ('PPPOE', 'PPPOE'), ('DHCP', 'DHCP'), ('HotSpot', 'HOTSPOT')], max_length=32, verbose_name='\u041f\u0440\u043e\u0442\u043e\u043a\u043e\u043b')),
                ('bytes_in', models.IntegerField(blank=True, null=True, verbose_name='IN')),
                ('bytes_out', models.IntegerField(blank=True, null=True, verbose_name='OUT')),
                ('session_status', models.CharField(blank=True, choices=[('ACTIVE', '\u0410\u043a\u0442\u0438\u0432\u043d\u0430'), ('NACK', '\u041d\u0435 \u0441\u0431\u0440\u043e\u0448\u0435\u043d\u0430'), ('ACK', 'C\u0431\u0440\u043e\u0448\u0435\u043d\u0430')], max_length=32, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('speed_string', models.CharField(blank=True, max_length=255, null=True)),
                ('acct_terminate_cause', models.CharField(blank=True, default=b'', max_length=128, verbose_name='\u041f\u0440\u0438\u0447\u0438\u043d\u0430 \u0440\u0430\u0437\u0440\u044b\u0432\u0430')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billservice.Account', verbose_name='\u0410\u043a\u043a\u0430\u0443\u043d\u0442')),
                ('ipinuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billservice.IPInUse')),
                ('nas_int', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nas.Nas', verbose_name='NAS')),
                ('subaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billservice.SubAccount', verbose_name='\u0421\u0443\u0431\u0430\u043a\u043a\u0430\u0443\u043d\u0442')),
            ],
            options={
                'verbose_name': 'RADIUS \u0441\u0435\u0441\u0441\u0438\u044f',
                'verbose_name_plural': 'RADIUS \u0441\u0435\u0441\u0441\u0438\u0438',
                'permissions': (('activesession_view', '\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440'),),
            },
        ),
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=40)),
                ('cause', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billservice.Account')),
                ('nas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nas.Nas')),
                ('subaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billservice.SubAccount')),
            ],
            options={
                'ordering': ['-datetime'],
                'verbose_name': 'RADIUS \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='RadiusStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField(blank=True, default=0)),
                ('alive', models.PositiveIntegerField(blank=True, default=0)),
                ('end', models.PositiveIntegerField(blank=True, default=0)),
                ('active', models.PositiveIntegerField(blank=True, default=0)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('nas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nas.Nas')),
            ],
        ),
    ]
