# -*- coding: utf-8 -*-

from django.conf.urls import url

from ebsweb.views import (
    AccountEmailView,
    AccountInfoView,
    AccountPasswordView,
    AccountServiceAddView,
    AccountServiceDelView,
    AccountServicesView,
    AccountSubAccountPasswordView,
    AccountSubAccountsView,
    AccountTariffView,
    AccountView,
    IndexView,
    MoneyCardView,
    MoneyPaymentView,
    MoneyPromiseView,
    MoneyTransferView,
    MoneyView,
    NotificationView,
    NotificationsView,
    SignoutView,
    SupportFollowupCreateView,
    SupportTicketCreateView,
    SupportTicketsView,
    SupportTicketView,
    SupportView
)
from ebsweb.views import statistics


app_name = 'ebsweb'

urlpatterns = [
    url('^$', IndexView.as_view(), name='index'),

    url('^signout/$', SignoutView.as_view(), name='signout'),

    url('^account$', AccountView.as_view(), name='account'),
    url('^account/info$', AccountInfoView.as_view(), name='account_info'),
    url('^account/tariff$', AccountTariffView.as_view(), name='account_tariff'),
    url('^account/subaccounts$',
        AccountSubAccountsView.as_view(),
        name='account_subaccounts'),
    url('^account/subaccounts/(?P<pk>\d+)/password$',
        AccountSubAccountPasswordView.as_view(),
        name='account_subaccount_password'),
    url('^account/services$',
        AccountServicesView.as_view(),
        name='account_services'),
    url('^account/services/connect$',
        AccountServiceAddView.as_view(),
        name='account_service_connect'),
    url('^account/services/disconnect$',
        AccountServiceDelView.as_view(),
        name='account_service_disconnect'),
    url('^account/email$',
        AccountEmailView.as_view(),
        name='account_email'),
    url('^account/password$',
        AccountPasswordView.as_view(),
        name='account_password'),

    url('^notifications/$',
        NotificationsView.as_view(),
        name='notification_list'),
    url('^notifications/(?P<pk>\d+)/$',
        NotificationView.as_view(),
        name='notification_detail'),

    url('^money/$', MoneyView.as_view(), name='money'),
    url('^money/payment$', MoneyPaymentView.as_view(), name='money_payment'),
    url('^money/promise$', MoneyPromiseView.as_view(), name='money_promise'),
    url('^money/transfer$',
        MoneyTransferView.as_view(),
        name='money_transfer'),
    url('^money/card$', MoneyCardView.as_view(), name='money_card'),

    url('^statistics/$',
        statistics.IndexView.as_view(),
        name='statistics'),
    url('^statistics/transactions/$',
        statistics.TransactionsView.as_view(),
        name='statistics_transactions'),
    url('^statistics/promises/$',
        statistics.PromisesView.as_view(),
        name='statistics_promises'),
    url('^statistics/sessions/$',
        statistics.SessionsView.as_view(),
        name='statistics_sessions'),
    url('^statistics/periodical_services/$',
        statistics.PeriodicalServicesView.as_view(),
        name='statistics_periodical_services'),
    url('^statistics/addon_services/$',
        statistics.AddonServicesView.as_view(),
        name='statistics_addon_services'),
    url('^statistics/one_time_services/$',
        statistics.OneTimeServicesView.as_view(),
        name='statistics_one_time_services'),
    url('^statistics/traffic_transactions/$',
        statistics.TrafficTransactionsView.as_view(),
        name='statistics_traffic_transactions'),
    url('^statistics/traffic/$',
        statistics.TrafficView.as_view(),
        name='statistics_traffic'),

    url('^support/$', SupportView.as_view(), name='support'),
    url('^support/tickets/$',
        SupportTicketsView.as_view(),
        name='support_tickets'),
    url('^support/tickets/create/$',
        SupportTicketCreateView.as_view(),
        name='support_ticket_create'),
    url('^support/tickets/(?P<pk>\d+)/$',
        SupportTicketView.as_view(),
        name='support_ticket'),
    url('^support/tickets/(?P<pk>\d+)/followup/$',
        SupportFollowupCreateView.as_view(),
        name='support_followup_create'),
]
