//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebsmon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ebsmon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение уже запущено!.
        /// </summary>
        internal static string AppAlredyRunned {
            get {
                return ResourceManager.GetString("AppAlredyRunned", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon appicon {
            get {
                object obj = ResourceManager.GetObject("appicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин пользователя и(или) пароль.
        /// </summary>
        internal static string AuthorizationError {
            get {
                return ResourceManager.GetString("AuthorizationError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap balance_ok {
            get {
                object obj = ResourceManager.GetObject("balance_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap balance_red {
            get {
                object obj = ResourceManager.GetObject("balance_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        internal static string BalanceTimerDelay {
            get {
                return ResourceManager.GetString("BalanceTimerDelay", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось установить связь с сервером. Пожалуйста проверьте сетевое соединение и повторите попытку.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение с сервером разорвано.
        /// </summary>
        internal static string ConnectionFault {
            get {
                return ResourceManager.GetString("ConnectionFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120000.
        /// </summary>
        internal static string ConnectionTimerDelay {
            get {
                return ResourceManager.GetString("ConnectionTimerDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /login/?next=/.
        /// </summary>
        internal static string ConnectionUrl {
            get {
                return ResourceManager.GetString("ConnectionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------.
        /// </summary>
        internal static string DefaultBalanceString {
            get {
                return ResourceManager.GetString("DefaultBalanceString", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap limit_ok {
            get {
                object obj = ResourceManager.GetObject("limit_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap limit_red {
            get {
                object obj = ResourceManager.GetObject("limit_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24000.
        /// </summary>
        internal static string NewsTimerDelay {
            get {
                return ResourceManager.GetString("NewsTimerDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBS новости провайдера.
        /// </summary>
        internal static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap popUp_skin {
            get {
                object obj = ResourceManager.GetObject("popUp_skin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://.
        /// </summary>
        internal static string ProtocolPrefix {
            get {
                return ResourceManager.GetString("ProtocolPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для подключения к серверу введите в настройках его адрес, а так же логин и пароль.
        /// </summary>
        internal static string RequiredSettingsError {
            get {
                return ResourceManager.GetString("RequiredSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при сохранении настроек. Возможно диск защищен от записи, либо у вас нет прав на создание файла..
        /// </summary>
        internal static string SavePreferencesError {
            get {
                return ResourceManager.GetString("SavePreferencesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /service_data/.
        /// </summary>
        internal static string ServiceDataUrl {
            get {
                return ResourceManager.GetString("ServiceDataUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebs монитор.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
