#!/bin/sh

case "$1" in
start)
        
        echo "Starting ebs processes"
	/etc/init.d/ebs_nfroutine start
	/etc/init.d/ebs_nf start
	/etc/init.d/ebs_rad_auth start
	/etc/init.d/ebs_rad_acct start
	/etc/init.d/ebs_core start
		;;
stop)
        echo "Stopping ebs processes"
	/etc/init.d/ebs_nfroutine stop
	/etc/init.d/ebs_nf stop
	/etc/init.d/ebs_rad_auth stop
	/etc/init.d/ebs_rad_acct stop
	/etc/init.d/ebs_core stop
        ;;
force-stop)
        echo "Stopping ebs processes"
	killall -9 nfroutine
	killall -9 nf 
	killall -9 rad_auth
	killall -9 rad_acct
	killall -9 core 
        ;;
restart)
        echo "Restarting ebs processes"
    $0 stop
    $0 start
    
        ;;

*)
        echo "Usage: `basename $0` {start|stop|force-stop}" >&2
        exit 64
        ;;
esac


