Document: ebs
Title: Debian ebs Manual
Author: <insert document author here>
Abstract: This manual describes what ebs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ebs/ebs.sgml.gz

Format: postscript
Files: /usr/share/doc/ebs/ebs.ps.gz

Format: text
Files: /usr/share/doc/ebs/ebs.text.gz

Format: HTML
Index: /usr/share/doc/ebs/html/index.html
Files: /usr/share/doc/ebs/html/*.html

  
