# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billservice', '0007_auto_20171110_1425'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('done_comment', models.TextField(blank=True, null=True, verbose_name='\u0424\u0438\u043d\u0430\u043b\u044c\u043d\u044b\u0439 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d')),
                ('done_date', models.DateTimeField(blank=True, null=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c \u0434\u043e ')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='\u0423\u0434\u0430\u043b\u0451\u043d')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_set', to='contenttypes.ContentType')),
                ('done_systemuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billservice.SystemUser', verbose_name='\u041a\u0435\u043c \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TableSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', jsonfield.fields.JSONField()),
                ('per_page', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
