# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpdesk.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billservice', '0007_auto_20171110_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=helpdesk.utils.attachment_path, verbose_name='File')),
                ('filename', models.CharField(max_length=100, verbose_name='Filename')),
                ('mime_type', models.CharField(max_length=30, verbose_name='MIME Type')),
                ('size', models.IntegerField(help_text='Size of this file in bytes', verbose_name='Size')),
            ],
            options={
                'ordering': ['filename'],
                'verbose_name': 'attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('subject', models.CharField(help_text='This will be prefixed with "[ticket.ticket] ticket.title". We recommend something simple such as "(Updated") or "(Closed)" - the same context is available as in plain_text, below.', max_length=100, verbose_name='Subject')),
                ('heading', models.CharField(help_text='In HTML e-mails, this will be the heading at the top of the email - the same context is available as in plain_text, below.', max_length=100, verbose_name='Heading')),
                ('plain_text', models.TextField(help_text='The context available to you includes {{ ticket }}, {{ queue }}, and depending on the time of the call: {{ resolution }} or {{ comment }}.', verbose_name='Plain Text')),
                ('html', models.TextField(help_text='The same context is available here as in plain_text, above.', verbose_name='HTML')),
            ],
            options={
                'ordering': ['template_name'],
                'verbose_name': 'email template',
                'verbose_name_plural': 'Email templates',
            },
        ),
        migrations.CreateModel(
            name='EscalationExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date', models.DateField(help_text='Date on which escalation should not happen', verbose_name='Date')),
            ],
            options={
                'verbose_name': 'escalation exclusion',
                'verbose_name_plural': 'Escalation exclusions',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('public', models.BooleanField(default=True, help_text='Public tickets are viewable by the submitter and all staff, but non-public tickets can only be seen by staff.', verbose_name='Public')),
                ('new_status', models.IntegerField(blank=True, choices=[(1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed')], null=True, verbose_name='New Status')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billservice.Account')),
                ('systemuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billservice.SystemUser')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'follow up',
                'verbose_name_plural': 'Follow ups',
            },
        ),
        migrations.CreateModel(
            name='IgnoreEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date', models.DateField(blank=True, editable=False, help_text='Date on which this e-mail address was added', verbose_name='Date')),
                ('email_address', models.CharField(help_text='Enter a full e-mail address, or portions with wildcards, eg *@domain.com or postmaster@*.', max_length=150, verbose_name='E-Mail Address')),
                ('keep_in_mailbox', models.BooleanField(default=False, help_text='Do you want to save emails from this address in the mailbox? If this is unticked, emails from this address will be deleted.', verbose_name='Save Emails in Mailbox?')),
            ],
            options={
                'verbose_name': 'ignored email',
                'verbose_name_plural': 'Ignored emails',
            },
        ),
        migrations.CreateModel(
            name='KBCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'knowledge base category',
                'verbose_name_plural': 'Knowledge base categories',
            },
        ),
        migrations.CreateModel(
            name='KBItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('votes', models.IntegerField(help_text='Total number of votes cast for this item', verbose_name='Votes')),
                ('recommendations', models.IntegerField(help_text='Number of votes for this item which were POSITIVE.', verbose_name='Positive Votes')),
                ('last_updated', models.DateTimeField(blank=True, help_text='The date on which this question was most recently changed.', verbose_name='Last Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.KBCategory')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'knowledge base item',
                'verbose_name_plural': 'Knowledge base items',
            },
        ),
        migrations.CreateModel(
            name='PreSetReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Only used to assist users with selecting a reply - not shown to the user.', max_length=100, verbose_name='Name')),
                ('body', models.TextField(help_text='Context available: {{ ticket }} - ticket object (eg {{ ticket.title }}); {{ queue }} - The queue; and {{ user }} - the current user.', verbose_name='Body')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'pre set reply',
                'verbose_name_plural': 'Pre set replies',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(help_text="This slug is used when building ticket ID's. Once set, try not to change it or e-mailing may get messy.", verbose_name='Slug')),
                ('email_address', models.EmailField(blank=True, help_text='All outgoing e-mails for this queue will use this e-mail address. If you use IMAP or POP3, this should be the e-mail  address for that mailbox.', max_length=254, null=True, verbose_name='E-Mail Address')),
                ('locale', models.CharField(blank=True, help_text='Locale of this queue. All correspondence in this queue will be in this language.', max_length=10, null=True, verbose_name='Locale')),
                ('allow_public_submission', models.BooleanField(default=False, help_text='Should this queue be listed on the public submission form?', verbose_name='Allow Public Submission?')),
                ('allow_email_submission', models.BooleanField(default=False, help_text='Do you want to poll the e-mail box below for new tickets?', verbose_name='Allow E-Mail Submission?')),
                ('escalate_days', models.IntegerField(blank=True, help_text='For tickets which are not held, how often do you wish to increase their priority? Set to 0 for no escalation.', null=True, verbose_name='Escalation Days')),
                ('new_ticket_cc', models.EmailField(blank=True, help_text='If an e-mail address is entered here, then it will receive notification of all new tickets created for this queue', max_length=254, null=True, verbose_name='New Ticket CC Address')),
                ('updated_ticket_cc', models.EmailField(blank=True, help_text='If an e-mail address is entered here, then it will receive notification of all activity (new tickets, closed tickets, updates, reassignments, etc) for this queue', max_length=254, null=True, verbose_name='Updated Ticket CC Address')),
                ('email_box_type', models.CharField(blank=True, choices=[(b'pop3', 'POP 3'), (b'imap', 'IMAP')], help_text='E-Mail server type for creating tickets automatically from a mailbox - both POP3 and IMAP are supported.', max_length=5, null=True, verbose_name='E-Mail Box Type')),
                ('email_box_host', models.CharField(blank=True, help_text='Your e-mail server address - either the domain name or IP address. May be "localhost".', max_length=200, null=True, verbose_name='E-Mail Hostname')),
                ('email_box_port', models.IntegerField(blank=True, help_text='Port number to use for accessing e-mail. Default for POP3 is "110", and for IMAP is "143". This may differ on some servers. Leave it blank to use the defaults.', null=True, verbose_name='E-Mail Port')),
                ('email_box_ssl', models.BooleanField(default=False, help_text='Whether to use SSL for IMAP or POP3 - the default ports when using SSL are 993 for IMAP and 995 for POP3.', verbose_name='Use SSL for E-Mail?')),
                ('email_box_user', models.CharField(blank=True, help_text='Username for accessing this mailbox.', max_length=200, null=True, verbose_name='E-Mail Username')),
                ('email_box_pass', models.CharField(blank=True, help_text='Password for the above username', max_length=200, null=True, verbose_name='E-Mail Password')),
                ('email_box_imap_folder', models.CharField(blank=True, help_text='If using IMAP, what folder do you wish to fetch messages from? This allows you to use one IMAP account for multiple queues, by filtering messages on your IMAP server into separate folders. Default: INBOX.', max_length=100, null=True, verbose_name='IMAP Folder')),
                ('email_box_interval', models.IntegerField(blank=True, default=b'5', help_text='How often do you wish to check this mailbox? (in Minutes)', null=True, verbose_name='E-Mail Check Interval')),
                ('email_box_last_check', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'queue',
                'verbose_name_plural': 'Queues',
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='User-provided name for this query', max_length=100, verbose_name='Query Name')),
                ('shared', models.BooleanField(default=False, help_text='Should other users see this query?', verbose_name='Shared With Other Users?')),
                ('query', models.TextField(help_text='Pickled query object. Be wary changing this.', verbose_name='Search Query')),
                ('systemuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billservice.SystemUser')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('source', models.CharField(choices=[(b'phone', '\u0422\u0435\u043b\u0435\u0444\u043e\u043d'), (b'helpdesk', 'HelpDesk'), (b'im', 'ICQ/Skype/Chat'), (b'personally', '\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u043e')], default=b'helpdesk', max_length=32, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
                ('notify_owner', models.BooleanField(default=True, verbose_name='Notify owner')),
                ('created', models.DateTimeField(blank=True, verbose_name='Created')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date this ticket was most recently changed.', verbose_name='Modified')),
                ('submitter_email', models.EmailField(blank=True, help_text='The submitter will receive an email for all public follow-ups left for this task.', max_length=254, null=True, verbose_name='Submitter E-Mail')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed')], default=1, verbose_name='Status')),
                ('on_hold', models.BooleanField(default=False, help_text='If a ticket is on hold, it will not automatically be escalated.', verbose_name='On Hold')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('hidden_comment', models.TextField(blank=True, help_text='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u0431\u0443\u0434\u0443\u0442 \u0432\u0438\u0434\u0435\u0442\u044c \u0442\u043e\u043b\u044c\u043a\u043e \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u044b.', null=True, verbose_name='\u0421\u043a\u0440\u044b\u0442\u044b\u0439 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439.')),
                ('resolution', models.TextField(blank=True, help_text='The resolution provided to the customer by our staff.', null=True, verbose_name='Resolution')),
                ('priority', models.IntegerField(blank=3, choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Very Low')], default=3, verbose_name='Priority')),
                ('last_escalation', models.DateTimeField(blank=True, editable=False, help_text='The date this ticket was last escalated - updated automatically by management/commands/escalate_tickets.py.', null=True)),
                ('account', models.ForeignKey(blank=True, help_text='\u0410\u043a\u043a\u0430\u0443\u043d\u0442, \u0441 \u043a\u043e\u0442\u043e\u0440\u044b\u043c \u0441\u0432\u044f\u0437\u0430\u043d\u0430 \u0442\u0435\u043a\u0443\u0449\u0430\u044f \u0437\u0430\u0434\u0430\u0447\u0430', null=True, on_delete=django.db.models.deletion.CASCADE, to='billservice.Account', verbose_name='Account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='billservice.SystemUser', verbose_name='\u0418\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Queue', verbose_name='Queue')),
            ],
            options={
                'get_latest_by': 'created',
                'verbose_name': 'ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='For non-user followers, enter their e-mail address', max_length=254, null=True, verbose_name='E-Mail Address')),
                ('can_view', models.BooleanField(default=False, help_text='Can this CC login to view the ticket details?', verbose_name='Can View Ticket?')),
                ('can_update', models.BooleanField(default=False, help_text='Can this CC login and update the ticket?', verbose_name='Can Update Ticket?')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Ticket')),
                ('user', models.ForeignKey(blank=True, help_text='User who wishes to receive updates for this ticket.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'ticket CC',
                'verbose_name_plural': 'Ticket CC',
            },
        ),
        migrations.CreateModel(
            name='TicketChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Field')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.FollowUp')),
            ],
            options={
                'verbose_name': 'ticket change',
                'verbose_name_plural': 'Ticket changes',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_pickled', models.TextField(blank=True, help_text='This is a base64-encoded representation of a pickled Python dictionary. Do not change this field via the admin.', null=True, verbose_name='Settings Dictionary')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.AddField(
            model_name='presetreply',
            name='queues',
            field=models.ManyToManyField(blank=True, help_text='Leave blank to allow this reply to be used for all queues, or select those queues you wish to limit this reply to.', to='helpdesk.Queue'),
        ),
        migrations.AddField(
            model_name='ignoreemail',
            name='queues',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for this e-mail to be ignored on all queues, or select those queues you wish to ignore this e-mail for.', to='helpdesk.Queue'),
        ),
        migrations.AddField(
            model_name='followup',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Ticket'),
        ),
        migrations.AddField(
            model_name='escalationexclusion',
            name='queues',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for this exclusion to be applied to all queues, or select those queues you wish to exclude with this entry.', to='helpdesk.Queue'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='followup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.FollowUp'),
        ),
    ]
