# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billservice', '0007_auto_20171110_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('flash', models.BooleanField(default=False)),
                ('backend', models.CharField(choices=[(b'sendsms.backends.websms.SmsBackend', b'websms.ru'), (b'sendsms.backends.smsru.SmsBackend', b'sms.ru'), (b'sendsms.backends.smspilotru.SmsBackend', b'smspilot.ru')], max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sended', models.DateTimeField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billservice.Account')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
